# Site settings
title: Zhang's Blog
SEOTitle: 张元的博客 | Zhang's Blog
header-img: img/post-bg-desk.jpg
email: zhangyuan360@163.com
description: "Every failure is leading towards success."
keyword: "ZY, Zhang's Blog, 张元的博客, zhangyuan, 张元, Deep learning, Python, JAVA"
url: "http://zhangyuan1997.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/zhangyuan1997/zhangyuan1997.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you going to be!"
sidebar-avatar: /img/zy_img.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     u/2940210645/home?wvr=5&c=spr_sinamkt_buy_hyww_weibo_t112
zhihu_username:     xiao-zhang-20-75/activities
github_username:    zhangyuan1997
facebook_username:  张元
#jianshu_username:   NULL
#twitter_username:   NULL




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
#comment:
#  enable: true    #是否开启Gitalk评论
#  client_id: 56a09e3795aa73fee15b   #生成的clientID
#  client_secret: 7a7fd7c84e064f609b963db028f35d64cbafa3cd  #同上
#  repo: https://github.com/zhangyuan1997/zhangyuan1997.github.io/issues    #仓库名称
#  owner: zhangyuan1997    #github用户名
#  admin: zhangyuan1997
#  distractionFreeMode: true #是否启用类似FB的阴影遮罩
#<!-- Gitalk 评论 start  -->
#
#<!-- Link Gitalk 的支持文件  -->
#<link rel="stylesheet" href="https://unpkg.com/gitalk/dist/gitalk.css">
#<script src="https://unpkg.com/gitalk@latest/dist/gitalk.min.js"></script> 
#<div id="gitalk-container"></div>     <script type="text/javascript">
#    var gitalk = new Gitalk({

#enable: true
#clientID: 56a09e3795aa73fee15b,
#clientSecret: 7a7fd7c84e064f609b963db028f35d64cbafa3cd,
#repo: zhangyuan1997.github.io,
#owner: zhangyuan1997,
#admin: zhangyuan1997,
#id: window.location.pathname,
#    
#   });
#    gitalk.render('gitalk-container');
#</script> 
#<!-- Gitalk end -->
var gitalk = new Gitalk({
  clientID: '56a09e3795aa73fee15b',
  clientSecret: '7a7fd7c84e064f609b963db028f35d64cbafa3cd',
  repo: 'zhangyuan1997.github.io',
  owner: 'zhangyuan1997',
  admin: ['zhangyuan1997'],
})

gitalk.render('gitalk-container')
# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 0a92c5ec7873a96787ef19c62291f308

# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Google",
        href: "https://www.google.com"
    },{
        title: "Zhang's Blog",
        href: "https://zhangyuan1997.github.io"
    },{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]
